# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  database: <%= ENV.fetch("QUBRICKS_DB_NAME") %>
  host: <%= ENV.fetch("QUBRICKS_DB_HOST") %>
  username: <%= ENV.fetch("QUBRICKS_DB_USER") %>
  password: <%= ENV.fetch("QUBRICKS_DB_PASS") %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: qubricks_test
  host: localhost
  username: abhishek
  password: password

production:
  <<: *default
  database: qubricks_prod
  host: localhost
  username: abhishek
  password: password
